CREATE_AD_BUTTON = ('css selector', 'button[class*="header__create-button"]')
USER_AVATAR = ('css selector', 'div[class*="header__user-avatar"]')
USERNAME = ('css selector', 'span[class*="header__user-name"]')
LOGOUT_BUTTON = ('css selector', 'button[class*="header__logout-button"]')
LOGIN_MODAL = ('css selector', 'div[class*="auth-modal__container"]')